### ISSUE TITLE
Unable to read configuration.

### ISSUE THREAD

**Issue by superchris** [8thlight/ex_state#3]
In my config.exs, I have added the following per the docs:

```
config :ex_state, repo: MyApp.Repo
```

When I try to do anything with ExState, it fails with:
```
** (ArgumentError) could not fetch application environment ExState for application :ex_state because configuration at ExState was not set
    (elixir 1.10.2) lib/application.ex:653: Application.fetch_env!/2
    (ex_state 0.2.0) lib/ex_state.ex:106: ExState.repo/0
    (ex_state 0.2.0) lib/ex_state.ex:113: ExState.create/1
```

**Comment by kevbuchanan** [comment]
Sorry, looks like that configuration change got out of sync with the documentation. The config you have there should work with version 0.3. Alternatively, 0.2 should work as:

```
config :ex_state, ExState, repo: MyApp.Repo
```
